version: "3.7"
services:
  web:
    image: openjdk:11
    restart: always
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./build/libs:/app
    ports:
      - "8080:8080"
    command: java -jar /app/todolist-0.0.1-SNAPSHOT.jar
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb